language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: ZPgqWaJpKq8kwvrn41Nkr6LW8+ykz72WVXncjPXA/3AasFYjsyIp7uibVAYVof65exAZ6v7/LR/MClTomZAK2qzPyrbe5pKJkwCLBw2V9Ztjot2Loto0jAGEV+KckIgQyqOr0mi+UbmMRxE6IqU4Hh/bQr4waCn/O5J8d2eXcSjieZcnFbA1S6uY/Ax+P+1hFh9HMpF+pv2m+WRpY+4dB9s65s+ZeJEOaOn8f69fG4Hef76p/BibvXSkEKDvNkJAOV3TqTl61YAWXFhtL6Wi1hfOeK/d9CG04zAZ2u2XM6JkQGC2XjWDKreU8/VuB3Cs0aDHvQf/kCvjPvuc6LK/gff35Cs5oeWvi9e/m6ubDJtB9f3MIcdq2cPmumV/6w5lYStCDau4+EltnhgD+f2k21c07Zmlm4V8sD44ld0ElUutzRT4l9LtqqmtkScPLNf+7JM14P9c9X8krr909XW3IoxxU8RQ4akVJj3QiT1huOIKtYtWLFA0sQF/KP62k4oVNO/DqPxb8RGV3yJeM6K4MBJ7xxoScuNBK4tI+UlUHo4qo9JuJ5qm/rg25K26rfLKjtJ1Tcq5HYcHFkge9FaDs3hC96kNyHxySOEueMk6d99XVhiWOlRfslbtjbX7NSRe/+jkxLlWvphP/ehYPVQM6iFbL0VJrH+Tbdnts05vvoE=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
