language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: YVsxmzo7R3QQiCoRAChb7oksNxVQgwbFmhWaP301tPaMBy5SY3EnVjli2W/ChDXhIQ9cqCx94MO6m6eQCWOI/FYC2vb2sUnl8ksp+t9keclt2Zsg42h5evde4EQM0QpPZ6K+MPei8oOTDlFa/hcEhwQwjzRMm6c5Cuo6hz67Ja/YRoSaxqS36oZSALw0tyGAVOuI9qQa+n24prEKFJCErTJLbbv8QS5phSld4X+/gA6HTacu+YJHIZBNGvmNoply9exu5TEWRcyN5qbdgxso/5pSEms961TcocxNQR9SNZPYighWPPAd3OsFCy0wtzCkmdno/58CqHfB88/u4veQmOHF9enudhiJKVpSy5CFbyHW4DPqeQPQxiUfIZAHUJm5uMxoDZk3XBXk8Zke7E0IV4CMVEUJlMSyyRcj6RzVYZkSJl7wApxzXtZk4IqDXT5f6NPvgNiUJtCARTEus29TQJNzwLjrykGutwFS3XPVXdgy1nvGLvwfcOx3MaATiE9aL2nVFIJ0Tyo9JA77czjTlJ6rOVRIGMsa4Z3gdGuK189bkSaybbjtoOnj1T2iUpfwPbVxlWcNEnekJDGQe77YSWdr5bbMfqY3I7DVblZCg8QPA4DQZB0v4neQH6ediVMq3pqokVrAkFPrWVfPuOlLmZtFwcvi5ZvvvgOAXDuHkrg=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
